// Generated by CoffeeScript 1.9.3
(function() {
  if (bowser.msie) {
    $("head").append('<link rel="stylesheet" href="stylesheets/tweaks_ie.css" type="text/css" />');
  }

}).call(this);

//# sourceMappingURL=tweaker.js.map
