// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    return $(".warning-close").click(function() {
      return $(".warning").slideUp();
    });
  });

}).call(this);

//# sourceMappingURL=warning.js.map
